"""
Django settings for mlhospital project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import sys
from pathlib import Path


def load_local_env(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()
        if not key or key in os.environ:
            continue

        if value and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ[key] = value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_local_env(BASE_DIR / '.env')
RUNNING_TESTS = 'test' in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-only-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False so production is safe by default; dev environments must set DJANGO_DEBUG=True explicitly.
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'
USE_REDIS_SERVICES = os.getenv(
    'USE_REDIS_SERVICES',
    'False' if DEBUG or RUNNING_TESTS else 'True',
).lower() == 'true'

ALLOWED_HOSTS = [host for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if host]

# Fail fast in production if SECRET_KEY/ALLOWED_HOSTS are not configured.
if not DEBUG and not RUNNING_TESTS:
    if SECRET_KEY in ('', 'dev-only-secret-key', 'replace-me'):
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be set to a strong random value when DEBUG=False."
        )
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            "DJANGO_ALLOWED_HOSTS must be configured when DEBUG=False."
        )


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # phải trước django.contrib.admin
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'accounts',
    'appoinment',
    'emr',
    'notifications',
    'crispy_forms',
    'bootstrapform',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mlhospital.urls'
ASGI_APPLICATION = 'mlhospital.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mlhospital.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
#         'NAME': os.getenv('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'vi'

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('vi', _('Tiếng Việt')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

AUTH_USER_MODEL = "accounts.user"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# CRISPY_TEMPLATE_PACK='bootstrap4'

# Upload limits (apply in both DEBUG and production)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', 5 * 1024 * 1024))   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 5 * 1024 * 1024))   # 5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.getenv('DATA_UPLOAD_MAX_NUMBER_FIELDS', 1000))

# Always-on security headers (safe to enable in DEBUG too)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# Production-only flags
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', 'True').lower() == 'true'
    CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', 60 * 60 * 24 * 30))   # 30 days default
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if os.getenv('USE_FORWARDED_PROTO', 'False').lower() == 'true' else None

# Google Gemini API Key
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.5-flash')
MAX_XRAY_UPLOAD_BYTES = int(os.getenv('MAX_XRAY_UPLOAD_BYTES', 5 * 1024 * 1024))
ALLOWED_XRAY_CONTENT_TYPES = tuple(
    content_type.strip()
    for content_type in os.getenv(
        'ALLOWED_XRAY_CONTENT_TYPES',
        'image/jpeg,image/png,image/webp',
    ).split(',')
    if content_type.strip()
)

# Email / SMTP
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.locmem.EmailBackend' if RUNNING_TESTS else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.sendgrid.net')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Medic <noreply@example.com>')

# Celery / Redis
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/1')
CELERY_TASK_ALWAYS_EAGER = os.getenv(
    'CELERY_TASK_ALWAYS_EAGER',
    'True' if RUNNING_TESTS or not USE_REDIS_SERVICES else 'False',
).lower() == 'true'
CELERY_TIMEZONE = TIME_ZONE

# Channels / Redis
CHANNEL_LAYER_BACKEND = os.getenv(
    'CHANNEL_LAYER_BACKEND',
    'inmemory' if RUNNING_TESTS or not USE_REDIS_SERVICES else 'redis',
).lower()
CHANNEL_REDIS_URL = os.getenv('CHANNEL_REDIS_URL', 'redis://127.0.0.1:6379/2')

if CHANNEL_LAYER_BACKEND == 'inmemory':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [CHANNEL_REDIS_URL],
            },
        }
    }

# SMS
SMS_PROVIDER = os.getenv('SMS_PROVIDER', 'twilio')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')

# Appointment policy
APPOINTMENT_CHANGE_DEADLINE_HOURS = int(os.getenv('APPOINTMENT_CHANGE_DEADLINE_HOURS', 4))

# Prevent Celery Eager mode from crashing views on SMTP errors
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_EAGER_PROPAGATES_EXCEPTIONS = False

# Logging
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} ({module}:{lineno}) - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'medic.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'accounts': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'appoinment': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'emr': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'home': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'notifications': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
    },
}

# =============================================================================
# Jazzmin Admin UI - https://django-jazzmin.readthedocs.io/
# =============================================================================
JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "Medic Admin",
    "site_header": "Medic - Hospital Management",
    "site_brand": "Medic",
    "site_logo": None,  # đường dẫn ảnh logo trong static/
    "login_logo": None,
    "site_icon": None,
    "welcome_sign": "Chào mừng tới hệ thống quản trị Medic",
    "copyright": "Medic Project - Đồ án tốt nghiệp",

    # Search nhanh
    "search_model": ["accounts.User", "appoinment.Appointment", "emr.EMRRecord"],

    # Top menu
    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Web app", "url": "/", "new_window": True},
        {"model": "accounts.User"},
        {"app": "appoinment"},
    ],

    # User menu (góc trên phải)
    "usermenu_links": [
        {"name": "Hỗ trợ", "url": "https://github.com/", "new_window": True},
        {"model": "accounts.user"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "accounts", "appoinment", "emr", "home", "notifications", "auth",
    ],

    # Icons mỗi app/model (dùng FontAwesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.User": "fas fa-user-md",
        "accounts.DoctorProfile": "fas fa-user-md",
        "appoinment.Appointment": "fas fa-calendar-alt",
        "appoinment.TakeAppointment": "fas fa-calendar-check",
        "appoinment.AppointmentChangeLog": "fas fa-history",
        "appoinment.DoctorReview": "fas fa-star",
        "appoinment.DirectMessage": "fas fa-comments",
        "emr.EMRRecord": "fas fa-file-medical",
        "emr.VitalSign": "fas fa-heartbeat",
        "emr.PrescriptionItem": "fas fa-prescription-bottle-alt",
        "home.MedicalHistory": "fas fa-notes-medical",
        "home.ChatMessage": "fas fa-robot",
        "notifications.NotificationPreference": "fas fa-cog",
        "notifications.AppointmentNotificationLog": "fas fa-envelope",
        "notifications.RealtimeNotification": "fas fa-bell",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # UI tweaks
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # Form layout
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "accounts.user": "collapsible",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

