# Generated by Django 5.2.12 on 2026-04-28 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0017_alter_appointment_options_and_more'),
        ('emr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emrrecord',
            index=models.Index(fields=['patient', '-created_at'], name='emr_emrreco_patient_d4ca9a_idx'),
        ),
        migrations.AddIndex(
            model_name='emrrecord',
            index=models.Index(fields=['doctor', '-created_at'], name='emr_emrreco_doctor__ded646_idx'),
        ),
    ]
