# Generated by Django 5.2.12 on 2026-04-14 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Bằng cấp chuyên môn', null=True)),
                ('experience', models.TextField(blank=True, help_text='Kinh nghiệm làm việc', null=True)),
                ('biography', models.TextField(blank=True, help_text='Giới thiệu bản thân', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
