# Generated by Django 4.2.5 on 2023-11-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0004_appointment_date_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeappointment',
            name='date',
        ),
    ]
