# Generated by Django 4.2.5 on 2023-11-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0005_remove_takeappointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
