# Generated by Django 4.2.5 on 2023-11-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0006_takeappointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
