# Generated by Django 5.2.12 on 2026-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0009_alter_appointment_id_alter_takeappointment_id'),
        ('appoinment', '0011_appointmentchangelog'),
    ]

    operations = [
    ]
