# Generated by Django 5.2.12 on 2026-04-28 11:59

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0016_directmessage_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='takeappointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('Diabetes Disease', 'Diabetes Disease'), ('Breast Cancer', 'Breast Cancer'), ('Dentistry', 'Dentistry'), ('Cardiology', 'Cardiology'), ('ENT Specialists', 'ENT Specialists'), ('Astrology', 'Astrology'), ('Neuroanatomy', 'Neuroanatomy'), ('Blood Screening', 'Blood Screening'), ('Eye Care', 'Eye Care'), ('Physical Therapy', 'Physical Therapy')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='appointmentchangelog',
            name='action',
            field=models.CharField(choices=[('booked', 'Booked'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'date'], name='appoinment__user_id_1bacc1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_active', 'date'], name='appoinment__is_acti_26f667_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentchangelog',
            index=models.Index(fields=['booking', '-created_at'], name='appoinment__booking_988318_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['booking', 'created_at'], name='appoinment__booking_ffe8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', 'is_read'], name='appoinment__sender__963eef_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor', '-created_at'], name='appoinment__doctor__620fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='takeappointment',
            index=models.Index(fields=['user', 'date'], name='appoinment__user_id_3222f9_idx'),
        ),
        migrations.AddIndex(
            model_name='takeappointment',
            index=models.Index(fields=['appointment', 'date'], name='appoinment__appoint_10fa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='takeappointment',
            index=models.Index(fields=['status', 'date'], name='appoinment__status_802ab9_idx'),
        ),
    ]
