# Generated by Django 5.2.12 on 2026-04-28 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='disease_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-created_at'], name='home_chatme_user_id_c7e4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['user', '-created_at'], name='home_medica_user_id_eae423_idx'),
        ),
    ]
